# Generated by Django 5.1.6 on 2025-04-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('cabeca', 'Proteção da cabeça'), ('auditiva', 'Proteção auditiva'), ('respiratoria', 'Proteção respiratória'), ('ocular_facial', 'Proteção ocular e facial'), ('superiores', 'Proteção dos membros superiores'), ('inferiores', 'Proteção dos membros inferiores'), ('quedas', 'Proteção contra quedas')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
