# Generated by Django 5.1.6 on 2025-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_app', '0002_equipamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=100)),
                ('colaborador', models.CharField(max_length=100)),
                ('data_emprestimo', models.DateField()),
                ('data_prevista', models.DateField()),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('em-uso', 'Em uso'), ('devolvido', 'Devolvido'), ('perdido', 'Perdido'), ('danificado', 'Danificado'), ('fornecido', 'Fornecido')], max_length=20)),
                ('condicoes', models.TextField()),
                ('data_devolucao', models.DateField()),
                ('observacoes', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
