# Generated by Django 5.2 on 2025-04-12 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_app', '0003_controle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epi_app.colaboradores'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epi_app.equipamentos'),
        ),
    ]
