# Generated by Django 5.2 on 2025-04-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epi_app', '0004_alter_controle_colaborador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controle',
            old_name='colaborador',
            new_name='colaborador_id',
        ),
        migrations.RenameField(
            model_name='controle',
            old_name='equipamento',
            new_name='equipamento_id',
        ),
    ]
